import './js/darkThemeToggle';
import './js/mobileMenu';
import './js/cocktails';
import './js/heroMobileSelect';
import './js/heroSearchLetter';
import './js/modalcocktail';
import './js/modalingr';
import './js/header';
// import { markUpRandomCocktails } from './js/cocktails';
// import { showNavigation } from './js/heroMobileSelect';
// import heroSearchLetter from './js/heroSearchLetter';
